name: scenespark-dev
version: '3.1'
services:
  api:
    image: ${DOCKER_REGISTY}/scenespark-api:${API_TAG}
    restart: always
    volumes:
      - ./api/.env:/app/.env
      - ./api:/app
      - ./pv-data/uploads:/tmp/videos

  web:
    image: ${DOCKER_REGISTY}/scenespark-web:${WEB_TAG}
    restart: always
    volumes:
      - ./pv-data/web/scenespark.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  nginx:
    image: nginx:latest
    volumes:
      - ./pv-data/nginx/scenespark.dev.conf:/etc/nginx/conf.d/default.conf
      - ./pv-data/uploads:/videos
    depends_on:
      - web
    ports:
      - "127.0.0.1:11000:80"

  # api-gpu:
  #   image: ${DOCKER_REGISTY}/scenespark-api:${API_TAG}
  #   restart: always
  #   # image: nvidia/cuda:11.0.3-base-ubuntu20.04
  #   # command: nvidia-smi
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./pv-data/downloads:/downloads
  #   deploy:
  #     # replicas: 2
  #     resources:
  #       limits:
  #         cpus: '4'
  #         memory: 6G
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   runtime: nvidia

  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD:
  #     MYSQL_DATABASE:
  #     MYSQL_USER:
  #     MYSQL_PASSWORD:
  #   volumes:
  #     - ./pv-data/mysql/data:/var/lib/mysql
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # redis:

  # weaviate:
