name: scenespark
services:
  api:
    image: ${DOCKER_REGISTY}/scenespark-api:${API_TAG}
    platform: linux/amd64
    restart: always
    volumes:
      - ./api/.env:/app/.env

  web:
    image: ${DOCKER_REGISTY}/scenespark-web:${WEB_TAG}
    platform: linux/amd64
    restart: always
    volumes:
      - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  nginx:
    image: nginx:latest
    platform: linux/amd64
    volumes:
      - ./nginx/scenespark.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - "127.0.0.1:8000:80"
