FROM --platform=linux/amd64 python:3.9-bookworm
ENV TZ=Asia/Shanghai
ARG DEBIAN_FRONTEND=noninteractive

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y vim curl && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app/
COPY . /app/

RUN pip3 install --upgrade pip wheel && pip3 install --no-cache-dir -r requirements.txt
