name: Pre-commit for API

on:
  pull_request:
    paths:
      - 'api/**'
  push:
    paths:
      - 'api/**'
    branches:
      - main
      - ci
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install pre-commit
      run: |
        pip install pre-commit

    - name: Run pre-commit
      run: |
        cd api
        ls -l
        pre-commit run --show-diff-on-failure --color=always --all-files
